### ISSUE TITLE
Key generated in other space

### ISSUE THREAD

**Issue by matheusbloebaum** [btnguyen2k/swift-rsautils#12]
I have a public key that was generated by another application. I have only the String, without the tags "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----".
I don't understand exactly if I have to add this tags or not.. could you please explain better?

**Comment by btnguyen2k** [comment]
Hi @matheusbloebaum,
You dont have t o add the tag. In fact you have to remove it, i.e. only use the text between the tags.

BTW: this project is merged with https://github.com/btnguyen2k/swiftutils and no longer maintained.
If possible, please switch to https://github.com/btnguyen2k/swiftutils for latest code.

Regards,

**Comment by matheusbloebaum** [comment]
Thanks!
