### ISSUE TITLE
Getting error using these algorithms 

### ISSUE THREAD

**Issue by santhoshnextbrain** [btnguyen2k/swift-rsautils#14]
AES algo name : AES/CBC/PKCS5PADDING
RSA algo name : RSA/ECB/OAEPWithSHA-1AndMGF1Padding

Generate AES keys 
RSA - AES keys encrypt using using public KEY 
 But this keys not validating server side.

**Comment by btnguyen2k** [comment]
Hi @santhoshnextbrain,

I am not sure I understand what you meant. In general, iOS supports certain paddings https://developer.apple.com/documentation/security/secpadding
So you need to choose a padding that is supported by iOS.

Please be noted that this library is no longer maintained, use https://github.com/btnguyen2k/swiftutils instead.
Below is an example using swiftutils

```swift
let privKey64 = "MIICXAIBAAKBgG5XFZDeSg10ZJGmR8a5FbU1mbSEULGBLj34ScEdqDzqgclR16Ed8AIXfcmqsTzWtIjyPzN0lOvn/xiC7hUH2uPpF/+xCFV16Tk/smLB8hTNj0ePVJALgLxI2oeeOZjy9Ax5vOt4ZyyZf8ttOt0G9RlX5H/p/uIyI8iiQIP46IWxAgMBAAECgYA0PPBN1J90fT07o2Bp2ahIUScCyn21e7YbypeIYPUMWe22FRQkCBtfsiVwO2qLpg50o1N+ldwHT596yEnVFRHwoD0dHEWYgUu6e0vLSyeTCWjg34hCQCNxKrFv9EQVvhZ5c18EuJgEc6w1oQ4NHFGNPLyhjywPcTgJ9QcRH0WhUQJBAM2zqCsfmiemB+Bgsp+i1XTNhn40fGKZDLToV/X7WCtavRIEvTsLJW3FXdILZXah7MsJVf9oD/0KQPt1kduHle0CQQCJUhA1IqvR2HYaGabFCu/VR6Ft/ON6yP+Rrikbw24uzqwjVy66zLwQzNd0XAMdtvjZC7nYp6XZMHDtlci72vZVAkAaiOBan7r8/lfpw8+G9DRg2tpMkWyyM1gGRiqCmqenAA9/sYjPgwKTBHCz1bCC+yRWlJ+5UK0vURFM3r+v9++JAkEAhQImzsDpelXXd0p3XY5NZeF+/GEiGdFMstfl2419UPtAgu60RZ1/YCp5WqyxG/wZp2oTNkaUfv3LtGULzOG3DQJBALHC7kbnnAhrGYOJ3r0fAsWT76wKbKAsgprlJObwnHEa1ZrBtXAoAxwhf6gGLwqtagFgyKtmTLDpSvk7wycyKR0="
let pubKey64 = "MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgG5XFZDeSg10ZJGmR8a5FbU1mbSEULGBLj34ScEdqDzqgclR16Ed8AIXfcmqsTzWtIjyPzN0lOvn/xiC7hUH2uPpF/+xCFV16Tk/smLB8hTNj0ePVJALgLxI2oeeOZjy9Ax5vOt4ZyyZf8ttOt0G9RlX5H/p/uIyI8iiQIP46IWxAgMBAAE="

let tagPublic = "com.github.btnguyen2k.ios.SwiftUtilsPlayground.public"
let tagPrivate = "com.github.btnguyen2k.ios.SwiftUtilsPlayground.private"
let keySecPub = try! RSAUtils.addRSAPublicKey(pubKey64, tagName: tagPublic)
let keySecPriv = try! RSAUtils.addRSAPrivateKey(privKey64, tagName: tagPrivate)
NSLog("Public Key : \(keySecPub!)")
NSLog("Private Key: \(keySecPriv!)")
if keySecPub==nil||keySecPriv==nil{
    return
}

let orgText = "This a string"
NSLog("Original text : \(orgText)")

let eData = RSAUtils.encryptWithRSAKey(orgText.data(using: .utf8)!, rsaKeyRef: keySecPub!, padding: SecPadding.OAEP)
if eData==nil{
    NSLog("ERROR: Encrypt with RSA public key")
    return
}
NSLog("Encrypted data: \(eData!)")

let dData = RSAUtils.decryptWithRSAKey(eData!, rsaKeyRef: keySecPriv!, padding: SecPadding.OAEP)
if dData==nil{
    NSLog("ERROR: Decrypt with RSA private key")
    return
}
NSLog("Decrypted data: \(dData!)")
NSLog("Decrypted text: \(String(data: dData!, encoding: .utf8)!)")
```

**Comment by santhoshnextbrain** [comment]
Thank you for reply.

I mean. i worked like this steps
1) AES and IV keys generated random at first time
2) those two keys encrypted using RSA - Public key.


after encryption convert to base64 two values.  1.encryptionKey , 2.encryption_iv. these two values need to send api headers.  but these values server not validating. but android working fine.


AES algorithm  name : AES/CBC/PKCS5PADDING
RSA algorithm name : RSA/ECB/OAEPWithSHA-1AndMGF1Padding

reference taken android - https://www.devglan.com/java8/rsa-encryption-decryption-java

Thanks you

**Comment by btnguyen2k** [comment]
Hi @santhoshnextbrain,

Can you post your Swift code? Thanks.

**Comment by santhoshnextbrain** [comment]
Hi @btngunyen2k.
sure.
===>
 func randomGenerateBytes(count: Int) -> Data? {
          let bytes = UnsafeMutableRawPointer.allocate(byteCount: count, alignment: 1)
          defer { bytes.deallocate() }
          let status = CCRandomGenerateBytes(bytes, count)
          guard status == kCCSuccess else { return nil }
          return Data(bytes: bytes, count: count)
      }
    
    
    func encryptionMethod() {
        
        var keyValueRSABase64 = String()
        var ivValueRSABase64 = String()
        let ivValue = randomGenerateBytes(count: kCCBlockSizeAES128)!
        let keyV = randomGenerateBytes(count: 256/8)!
        
        
        let PUBLICKEY = ""
        // tag name to access the stored public key in keychain
        let TagPublicKey = "com.nb.App"
        
        
        
        let encryptedDataAES = RSAUtils.encryptWithRSAPublicKey(keyV, pubkeyBase64: PUBLICKEY, keychainTag: TagPublicKey)
        
        if ( encryptedDataAES == nil ) {
            print("Error while encrypting")
        } else {
            let encryptedDataText = encryptedDataAES!.base64EncodedString(options: NSData.Base64EncodingOptions())
            keyValueRSABase64 = encryptedDataText
            print("Encrypted with pubkey:\n \(encryptedDataText)")
        }
        
        
        
        let encryptedDataAESIV = RSAUtils.encryptWithRSAPublicKey(ivValue, pubkeyBase64: PUBLICKEY, keychainTag: TagPublicKey)
        if ( encryptedDataAESIV == nil ) {
            print("Error while encrypting")
        } else {
            let encryptedDataTextIV = encryptedDataAESIV!.base64EncodedString(options: NSData.Base64EncodingOptions())
            ivValueRSABase64 = encryptedDataTextIV
            print("Encrypted with pubkey:\n \(encryptedDataTextIV)")
        }
        
        
        print("encryption-key:\(keyValueRSABase64)")
        print("encryption-iv:\(ivValueRSABase64)")
    }

**Comment by btnguyen2k** [comment]
Hi @santhoshnextbrain,

I assume the business logic and other settings (keys and tags) are correct. Then the AES Key and IV should be encrypted correctly.
The issue would be somewhere:
- Is it correctly transferred from iOS to server? A log at server side would be sufficient to verify this.
- Is iOS and server using the same padding? `RSAUtils.encryptWithRSAPublicKey(Data, String, String)` uses `SecPadding.PKCS1`. You may wish to use `RSAUtils.encryptWithRSAKey(Data, SecKey, SecPadding)` to supply custom padding (see example in my previous comment).

Best reagards,

**Comment by santhoshnextbrain** [comment]
Hi @btnguyen2k 
Thank You for responding quickly.

Can i know, Used padding .OAEP, .PKCS1 .   these padding are under which algorithm?



Ex:-
 Please check bellow method used algorithm "rsaEncryptionOAEPSHA1" :

let encryptedMessageDataText:Data = SecKeyCreateEncryptedData(publicSecKey!, .rsaEncryptionOAEPSHA1, plainData! as CFData,error) as Data?{
}

**Comment by btnguyen2k** [comment]
Hi @santhoshnextbrain,

For that you need to verify it yourself. iOS document lists only these paddings: https://developer.apple.com/documentation/security/secpadding

**Comment by santhoshnextbrain** [comment]
HI @btnguyen2k :

OK. Thank you so much for sharing your knowledge and Help.

**Comment by btnguyen2k** [comment]
Hi @santhoshnextbrain,

I just tested myself with the following:

Encryption from iOS:
```swift
/* 2048-bit RSA key pair */
let privKey64 = "MIIEowIBAAKCAQEApjYx0U5cJLAkx3ATqxk5qv7raEv/romlDPa2WFjahplh4lFXD9dzX1fDLWPqwlxp/ZuUlYf3p50oVogoUe2+5IQ/qtpUEaB5Acc8qcx9FekKvxSG8SmCtc3NsC08Bsd6Rw4M6MGB51xeuSbB3cqh7UUhKiFZflUnudMJ7t3mPwEyvgLpA44MJ7nYnG28S0NqTUnM24IVRbPBYvd8xT6swum4nvwGQvbzP8PKqdYd/LBXkCzWMig9ZplGDBNPrAywoWdaGeYIoK4OO3ZhkSKGqAFSEZBj8HYNpHsj3NBqXsRfh0gaAV8tOKP79sBqa6hCL5LQr+nj5QIqYqa4NmUWFQIDAQABAoIBAEQmHmD6Zw9n5XyceIQD0MBKy0y1NH1k1HavRW6N5/OeOiMoRLErHpPuEQmwWRYd/BtOyipRWHqyFlL8esO03jsl+lDcOfIMQPE4tqfMP1FXft9/1CBXa8+NNZPRyDXjXkB6A1L/3Hp3RiNWP9Dnf2MgoAt9JwuEcMhhPkZhV0FnW8SeWh5bdmZstGsoLg6adtR8Bcz0RmE41SCzfIdWNxPUfwuMSitDonTttUOWEvYju8uTSt3VfPcYt8WBNj7ijFwWPRIiVYy118DNpKsmK3ZQQ88diNClPoXbb1XD7FRVhc5x9TqWl7Mpw3T9Wd6O8d+izn2Ny3Om6m0n5CpwJDUCgYEA3cNVvs/aWeqo0ov9QKTNv+XK1LsczAJEfNUa8IPpj35zzy21lC2cOWKKXaQeyIwI9YjeKD7OGdOdynN+Zpv6v+z/+4VNvf5BKWYwBTNaHjeo9gvJY8y49ZUAxXJgT6+wuc+PHVBOtowBed50V3aq+eYcYrkaIeOF9nC7cTcfNo8CgYEAv99SwZHXmxbJOF47LWqk5+k8bhIuPtruU3flW7Aw6tTARXQtf0N1GXPkaiRycFUuTg6YO7YNUK3NyuWKexAoZJ+IsYJp3CZBmUmRMN43xdPRtCTI0iQ7xdxMoyuTiMQTXqWEzSCvMK6LmXA7ss+2RgYGJxRto6OVZDyWsY2y2xsCgYBIoga+hWN12dbLhxA+kPvWo1PokxReeUunO0Ekj3/7AKa7r7PuQXYOkYjSHMP8WWlByj9BHTjx2o6u1V8MCoB5Rg2des64sML05URLH8OfbAmJ9NhUOKRHwzLKeKi00M1oPmQYbMorHfYJzWN7liFv0f9wEkJN4TBqRAgQj8ZIXwKBgQCCwPiPawjH6pZDsIuZXqR0WhBRXlhfgyiIfxsxCXe8gDFq40oiAOFq7/xHjQDjpljA3tdFUcHvKhIk45okVRWBxOoNNbdYTEXF5UlpSPYu/TNaFPs5oXGOW5tqUsbem+grRpaih1R702bUsJQuPbiULYTB2v0AV/j1bwiuhMbO4wKBgGTPf+XhpBdZLMfiuUI0hrVB/QminXMNsw4BU5CDW3K4hzo2fKKVhPkIKZ2RgU0hAqODdyJaEft0wN3X4fq+Tu4KIqz6RR8+BVzfUaAEyUE9E/UHLnO380iQ+7HwkSBGERXgFpZDf++L5sKT+pDT2jZ4tLyE8axIqWTWa22WV8J/"
let pubKey64 = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApjYx0U5cJLAkx3ATqxk5qv7raEv/romlDPa2WFjahplh4lFXD9dzX1fDLWPqwlxp/ZuUlYf3p50oVogoUe2+5IQ/qtpUEaB5Acc8qcx9FekKvxSG8SmCtc3NsC08Bsd6Rw4M6MGB51xeuSbB3cqh7UUhKiFZflUnudMJ7t3mPwEyvgLpA44MJ7nYnG28S0NqTUnM24IVRbPBYvd8xT6swum4nvwGQvbzP8PKqdYd/LBXkCzWMig9ZplGDBNPrAywoWdaGeYIoK4OO3ZhkSKGqAFSEZBj8HYNpHsj3NBqXsRfh0gaAV8tOKP79sBqa6hCL5LQr+nj5QIqYqa4NmUWFQIDAQAB"

// encrypt with SecPadding.OAEP using the code in my previous comment
// encrypted data (in base64):
// JAKX1qnZpMNI6glXghwCx45efCdLAC9UNNAseqiSQhid7wQfDj37ojQ5jGdvVgA6AtOnJs0/A7F6XzVaInSxQxAz6S9l5NNpvzafDTuCPV6r6ixqNVQAQkq1miy6Ns5xh7suMMZ6I53ic+NaMyDGHZh4w5TEvzXj2XFxYVmJHU882BKVheNKlDuYyF5/PSUzfaE7XWPfH+1d9t6FemkagiqcFZ8TEX7htl2RKHoL258LCi7nh/1bYOWMqh2k+Xf30t34HRkgz9zvxYEegUpVCp+EnzeccwZx/shDvE3O0j0PFGf0wQbRDD0MAXth2MOT/ijkVQtueGu2nQm1Mg95/g==
```

I then used the same keypair to decrypt the encrypted-data from Java code using tranformation `RSA/ECB/OAEPWithSHA-1AndMGF1Padding` and it worked (note `RSA/ECB/OAEPWithSHA1AndMGF1Padding` also worked).

Hope it helps.
