### ISSUE TITLE
[Question] Is it to generate the keys in Swift? 

### ISSUE THREAD

**Issue by Godlex** [btnguyen2k/swift-rsautils#3]
Hi, 

first of all thank you for this awesome project! It is really what I needed, thank you! :)
I have one question about the keys because they have to be in PKC8 format as I figured out of this issue:

http s://github.com/btnguyen2k/swift-rsautils/issues/2

Is it somehow possible to generate a public and a private key in swift for this format? Or will you support more formats soon? Or do I have to make them with ssh and format them to PKC8?

Sorry if this is a stupid question I am pretty new to security (especially for Swift)

**Comment by arik-so** [comment]
Hi, I, too, would love to see support for key generation in this library. Thanks!

**Comment by btnguyen2k** [comment]
Hi @Godlex,

Thank you very much for your support.
This lib is to work with key(s) pre-created somewhere (e.g. with openssl tool).
The usual usage would be like this:
- The server generate pair of key; it keeps the private key and distribute the public key freely.
- The client (iOS app) uses the public key to encrypt data before sending to the server.

It's rare case to generate the key pair in Swift, but I'll try to make a function to do that in a future update.

Cheers,
