### ISSUE TITLE
About keychain -34018

### ISSUE THREAD

**Issue by mohpor** [btnguyen2k/swift-rsautils#4]
Hi,
This is a very nice library to work RSA in iOS, but unfortunately, as much other libraries do, suffers from the plague of keychain access: -34018. [(Read on Apple Developers Forum)](https://forums.developer.apple.com/thread/4743)

However, the problem here is that accessing keychain is only required to retrieve the public or private key. Is there a workaround for this? Can we just produce the RSA key without the need of keychain?

I'm on the verge of going completely mad. (as a lot of other developers do)
Thanks a lot.

**Comment by btnguyen2k** [comment]
It could be too late to response but it's still better than never :-)
See this link if it helps: http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-beta-gm-in-ios-10-simulator/38543243
