### ISSUE TITLE
Update to Swift 2.2

### ISSUE THREAD

**Issue by LiborZ** [btnguyen2k/swift-rsautils#5]
Are you planning to update this library to Swift 2.2 and other updates in future? Thanks

**Comment by LiborZ** [comment]
Any comment? And what about update to Swift 3.0 when it's released?

**Comment by btnguyen2k** [comment]
Hi @LiborZ ,

This pull request (https://github.com/btnguyen2k/swift-rsautils/commit/89315ee98fdd2267fae88c4363124bc7934172c7) should work with Swift 2.2

Regarding Swift 3.0, when it is out, I will test against Swift 3.0 but it should work without any changes.

Best regards,
Thanh Nguyen

**Comment by LiborZ** [comment]
It's okay now. I updated classes and no warnings. I just don't know there is update. Thanks
