### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by neetrath** [btnguyen2k/swift-rsautils#7]
Hello,
Thank you for made this utility. It's very useful.

These codes are made for support Swift 2. So some syntax will be deprecated is Swift 3 (e.g. ++) 
Please update it.

Thanks for your attention.

**Comment by btnguyen2k** [comment]
Hi @neetrath, thanks for your support.

I have plan to migrate to Swift 3, but it will take a while :-)

Best regards,
Thanh Nguyen

**Comment by lu1sprz** [comment]
if you can update this i will be very thankful, i could try to upgrade it but im still a noob

**Comment by larry12222** [comment]
Yea,it always return nil now,may u update it?

**Comment by btnguyen2k** [comment]
Hi all, there was a bug in last commit and it has been fixed. It should work now.
If you got error -34018, see this link http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-beta-gm-in-ios-10-simulator/38543243#38543243

Cheers,
