### ISSUE TITLE
RSA cho Android1

### ISSUE THREAD

**Issue by hoanghiephui** [btnguyen2k/swift-rsautils#8]
Anh có thể viết một thư viện dành cho Android mà tương thích với thuật toán anh đang sử dụng cho ios không ạ.

**Comment by btnguyen2k** [comment]
Nếu bạn code Java trên Android thì ngay trong Java đã có sẵn các class để bạn mã hoá/giải mã với RSA key. Bạn có thể tham khảo
http://stackoverflow.com/questions/12471999/rsa-encryption-decryption-in-android
http://stackoverflow.com/questions/37173777/android-rsa-encryption-from-public-string

**Comment by hoanghiephui** [comment]
Cám ơn anh đã trả lời
Thực ra thì e cũng đã viết, nhưng Em đang gặp phải một vấn đề là public key của Android gửi cho ios thì khi encryptor thông tin gửi lại cho Android thì Android decryptor được, Nhưng khi e dùng public key của ios gửi cho Android để encryptor thì Android bị lỗi.

Em mạn phép hỏi anh là liệu anh có thể viết một lib dựa vào thuật toán tương tự như bản anh đang viết cho ios không ạ.

**Comment by hoanghiephui** [comment]
Khi em nhận string public key từ máy ios thì em EncodedKeySpec string đó sang PublicKey thì em bị lỗi như này.
`10-20 14:23:03.939 17380-17380/com.e2e.message W/System.err: java.security.spec.InvalidKeySpecException: encoded key spec not recognised
10-20 14:23:03.943 17380-17380/com.e2e.message W/System.err:     at org.spongycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(BaseKeyFactorySpi.java:52)
10-20 14:23:03.943 17380-17380/com.e2e.message W/System.err:     at org.spongycastle.jcajce.provider.asymmetric.rsa.KeyFactorySpi.engineGeneratePublic(KeyFactorySpi.java:130)
10-20 14:23:03.943 17380-17380/com.e2e.message W/System.err:     at java.security.KeyFactory.generatePublic(KeyFactory.java:172)`

Mặc dù nếu ios hoặc Android gửi thông tin riêng lẻ cho nhau thì không sao cả.
